### PR TITLE
Replace deprecated patchesStrategicMerge with current patches

### PR DESCRIPTION
**Pull request by gllb**
This MR aim to fix https://github.com/helmfile/helmfile/issues/1237.

### CODE REVIEW

**Comment by yxxhero** [comment]
@gllb please fix DCO.

**Comment by yxxhero** [comment]
could you add some tests?

**Comment by gllb** [comment]
You me to adapt existing one or create new one ? Because the existing test should cover this patch, or I miss something ?

**Comment by yxxhero** [comment]
@gllb ok. please fix DCO: https://github.com/helmfile/chartify/pull/85/checks?check_run_id=24558803618

**Comment by yxxhero** [comment]
In your local branch, run: git rebase HEAD~1 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin support_current_kustomize_patches

**Comment by genofire** [comment]
@gllb thank you for your work here :bouquet:

**Pull request merged**
